---
title: "Clean Low Birth Weight Data"
date: "2022-10-02 <br> Updated: `r Sys.Date()`"
---

# ⭐️ Overview

In this file, we clean the low birth weight data for Epidemiology III. Then we save it as an Rds file. 


# 📦 Load packages

```{r message=FALSE}
library(dplyr, warn.conflicts = FALSE)
library(haven)
library(readr)
library(codebookr)
```

# 📥 Import data 

```{r}
lowbwt <- read_dta("lowbwt.dta")
```

```{r}
dim(lowbwt)
```


# 🚧 Data management

Create factor versions of all variables

```{r}
ny <- c("No", "Yes")
```

```{r}
lowbwt <- lowbwt %>%
  mutate(
    id      = as.character(id),
    race_f  = factor(race, 1:3, c("White", "Black", "Other")),
    low_f   = factor(low, 0:1, ny),
    smoke_f = factor(smoke, 0:1, ny),
    ht_f    = factor(ht, 0:1, ny),
    ui_f    = factor(ui, 0:1, ny)
  )
```

```{r}
dim(lowbwt) # 189  15
```

Reorder variables 

```{r}
lowbwt <- lowbwt %>% 
  select(
    id, low, low_f, age, lwt, race, race_f, smoke, smoke_f, ptl, ht, ht_f, ui, ui_f, ftv
  )
```

```{r}
dim(lowbwt) # 189  15
```


# Add attributes for codebookr

```{r}
for (i in seq_along(names(lowbwt))) {
  cat(paste0('
    cb_add_col_attributes( \n    ',
      "  ", names(lowbwt)[i], ', \n    ',
      "  ", 'description = ""', ', \n    ',
      "  ", 'value_labels = ""
    ) %>%
  '))
}
```

```{r}
ny <- c("No" = 0, "Yes" = 1)
```

```{r}
lowbwt <- lowbwt %>% 
    cb_add_col_attributes(
      id, 
      description = "Identification code."
    ) %>%
  
    cb_add_col_attributes( 
      low, 
      description = "Low birth weight (<=2,500 grams).", 
      value_labels = c("BWT > 2500g" = 0, "BWT <= 2500g" = 1)
    ) %>%
  
    cb_add_col_attributes( 
      low_f, 
      description = "Low birth weight (<=2,500 grams)."
    ) %>%
  
    cb_add_col_attributes( 
      age, 
      description = "Age of mother in years."
    ) %>%
  
    cb_add_col_attributes( 
      lwt, 
      description = "Weight of mother at last menstrual period in pounds."
    ) %>%
  
    cb_add_col_attributes( 
      race, 
      description = "Mother's race.",
      value_labels = c("White" = 1, "Black" = 2, "Other" = 3)
    ) %>%
  
    cb_add_col_attributes( 
      race_f, 
      description = "Mother's race."
    ) %>%
  
    cb_add_col_attributes( 
      smoke, 
      description = "Smoking status during pregnancy.",
      value_labels = ny
    ) %>%
  
    cb_add_col_attributes( 
      smoke_f, 
      description = "Smoking status during pregnancy."
    ) %>%
  
    cb_add_col_attributes( 
      ptl, 
      description = "History of premature labor (count of previous occurrences)."
    ) %>%
  
    cb_add_col_attributes( 
      ht, 
      description = "History of hypertension.",
      value_labels = ny
    ) %>%
  
    cb_add_col_attributes( 
      ht_f, 
      description = "History of hypertension."
    ) %>%
  
    cb_add_col_attributes( 
      ui, 
      description = "Presence of uterine irritability.",
      value_labels = ny
    ) %>%
  
    cb_add_col_attributes( 
      ui_f, 
      description = "Presence of uterine irritability."
    ) %>%
  
    cb_add_col_attributes( 
      ftv, 
      description = "Number of physician visits during the first trimester."
    )
```


# Create codebook

```{r}
codebook <- codebook(
  lowbwt,
  title = "For the Low Birth Weight Study",
  description = "These data are described in Applied Logistic Regression (2013) by Hosmer & Lemeshow, section 1.6.2, page 24. This codebook was created with the codebookr package (https://github.com/brad-cannell/codebookr)."
)
```

```{r}
print(codebook, "Codebook lowbwt.docx")
```


# Save clean data as an Rds file

```{r}
write_rds(lowbwt, "lowbwt.rds")
```


# 🗑 Clean up

```{r}
rm(list = ls())
```

