---
title: "Lab Warm-up: Module Name"
output: html_notebook
---

# Load packages

Remember, it's considered a best practice to load all the packages that your file will use up at the top of the file. If you have not yet installed a package, you will need to do so by running `install.packages("package name")` in the R console. For example, to install the `dplyr` package, you would run `install.packages("dplyr")`. However, you typically **do not** want to type the code to install the package here in your Rmd file. That is because you only need to install the package once on a given computer. Not every time you run your R code.

```{r}
library(dplyr, warn.conflicts = FALSE) # The "warn.conflicts" part is optional
```

# Overview

Here is an overview of what we will cover in this lab warm-up. You will be talking about the purpose of the code below during the live lab warm-up session; however, some written material here will probably be helpful to students who are reviewing the code later, outside of the lab session. 

# Section 1

The rest of what's in here will be fairly lesson specific. At least for now. 
