---
title: "Lab Warm-up: Module Name"
format:
  html:
    embed-resources: true
---

# 🛑 Formatting (delete this section before posting to Canvas) 🛑

* Please name this file `lab_warm_up_module_name.qmd`.
* The Overview section, each task number, and each question number should be written as a level-one headers (e.g., `# Task 1`).
* All R code being run, should be put into R code chunks.
* All R code being discussed in the text should be placed inside backticks (e.g., `install.packages("dplyr")`).
* R package names being discussed in the text should be formatted as code (e.g., "...the `dplyr` package...). 
* When functions are discussed in the text, they should be formatted as code and empty parentheses added to the end of the function name (e.g., "The `tibble()` function can be used to create data frames…").
* Data set/frame names, variable names, and other key words should be written with **bold** text (e.g., "Please download **chocolate study 1.xls**".
* There should be 2 line breaks (returns) immediately above level-one headers. There should be 1 line break (return) immediately above all other headers.
* There should be one line break (return) immediately above each code chunk. There should be at least 1 line break immediately below each code chunk. If the the code chunk is immediately followed by a level-one header, then there will be two line breaks.

# Load packages

Remember, it's considered a best practice to load all the packages that your file will use up at the top of the file. If you have not yet installed a package, you will need to do so by running `install.packages("package name")` in the R console. For example, to install the `dplyr` package, you would run `install.packages("dplyr")`. However, you typically **do not** want to type the code to install the package here in your Quarto file because you only need to install the package once on a given computer. Not every time you run your R code.

```{r}
#| label: load-packages
library(dplyr, warn.conflicts = FALSE) # The "warn.conflicts" part is optional
```

# Overview

Here is an overview of what we will cover in this lab warm-up. You will be talking about the purpose of the code below during the live lab warm-up session; however, some written material here will probably be helpful to students who are reviewing the code later, outside of the lab session. 

# Section 1

The rest of what's in here will be fairly lesson specific. At least for now. 
