---
title: "Lab: Confounding"
format:
  html:
    embed-resources: true
---


# Load packages

Remember, it's considered a best practice to load all the packages that your file will use up at the top of the file. If you have not yet installed a package, you will need to do so by running `install.packages("package name")` in the R console. For example, to install the `dplyr` package, you would run `install.packages("dplyr")`. However, you typically **do not** want to type the code to install the package here in your Quarto file because you only need to install the package once on a given computer. Not every time you run your R code.

```{r}
#| label: load-packages
library(dplyr, warn.conflicts = FALSE) # The "warn.conflicts" part is optional
```


# Overview

In this lab, we will walk through multiple scenarios related to confounding.

## Question 1

See Canvas. There are no R calculations for this question.

## Question 1

See Canvas. There are no R calculations for this question.

## Question 2

See Canvas. There are no R calculations for this question.

## Question 3

See Canvas. There are no R calculations for this question.

## Question 4

See Canvas. There are no R calculations for this question.

## Question 5

See Canvas. There are no R calculations for this question.

## Question 6

See Canvas. There are no R calculations for this question.

## Question 7

See Canvas. There are no R calculations for this question.

## Question 8

See Canvas. There are no R calculations for this question.
